config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'deliver_addresses', to: 'users/registrations#new_deliver_address'
    post 'deliver_addresses', to: 'users/registrations#create_deliver_address'
  end
  root 'products#index'
  resources :users do
    collection do
      get 'logout'
    end
  end
  resources :credit_cards
  resources :brands, only: [:create]
  resources :products do 
    member do
      get 'pay'
      get 'purchase'
    end
    collection do
      get 'paid'
      get 'search_category_children'
      get 'search_category_grandchildren'
      get 'search'
    end
    resources :comments
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :user, :customer_id, :card_id, presence: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_api_key, only: [:edit, :create, :show, :delete]

  require "payjp"

  def new
    @card = CreditCard.new
    card = CreditCard.where(id: params[current_user.id])
    redirect_to credit_card_path if card.exists?
  end
  
  def edit
  end

  def create
    if params['payjp-token'].blank?
      redirect_to new_credit_card_path
    else
      customer = Payjp::Customer.create(
        description: '登録テスト',
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        flash[:notice] = 'クレジットカードを登録しました'
        redirect_to user_path(current_user)
      else
        flase[:alert] = 'クレジットカードが正しく登録できませんでした'
        render :new
      end
    end
  end

  def destroy
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to root_path
    else
      @customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer.delete
      @card.delete
      redirect_to user_path(current_user)
    end
  end

  def show
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to new_credit_card_path
    else
      @customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = @customer.cards.retrieve(@card.card_id)
      @default_card_information = @customer.cards.retrieve(@card.card_id)
    end
  end

  private 
  
  def set_api_key
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
  end
end

app/views/credit_cards/new.html.haml
.header
  = render 'shared/header'

.breadCrumb-nav
  - breadcrumb :card
  = breadcrumbs separator: " &rsaquo; ", class: "breadCrumb-nav__list"

.SignupCard
  .SignupCard__box
    .SignupCard__box__body
      %h2.SignupCard__box__body__title カード情報入力
      = form_with model: @card, url: credit_cards_path, id: 'card_token', class: "SignupCard__box__body__input", local: true do |f|
        .SignupCard__box__body__input__form
          .SignupCard__box__body__input__form__content
            %label.card__info カード番号
            %span.notify 必須
            %br
            = f.text_field :number, class: "input", size: "16", placeholder: "半角数字のみ", id: "card_number"
        .SignupCard__box__body__input__form
          .SignupCard__box__body__input__form__content
            %label.card__info 有効期限
            %span.notify 必須
            %br
            %select#exp_month{name: "exp_month", type: "text", class: "input_half"}
              %option{value: ""} -----
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月
            %select#exp_year{name: "exp_year", type: "text",  class: "input_half"}
              %option{value: ""} -----
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年
        .SignupCard__box__body__input__form
          .SignupCard__box__body__input__form__content
            %label.card__info セキュリティコード
            %span.notify 必須
            %br
            = text_field "cvc", "", class: "input", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        .SignupCard__box__body__input__form
          .SignupCard__box__body__input__form__content
            = f.submit 'カードを登録する', class: "SignUp-btn", id: "token_submit"

app/views/credit_cards/show.html.haml
.header
  = render 'shared/header'

.breadCrumb-nav
  - breadcrumb :card_show
  = breadcrumbs separator: " &rsaquo; ", class: "breadCrumb-nav__list"

.Card
  .Card__body 
    %p 登録中のカード
    .Card__body__details
      - if @card.blank?
        登録しているカードはありません
      - else 
        %ul 
        = "カード番号：**** **** **** #{@card_information.last4}"
        %br
        = "有効期限：#{@card_information.exp_month.to_s} / #{@card_information.exp_year.to_s.slice(2,3)}"
    .Card__body__button
      -if @card.blank?
        = link_to '登録する', new_credit_card_path
      - else
        = link_to '削除する', credit_card_path(@card), method: :delete, class: "button"
      = link_to 'トップページへ戻る', root_path, class: "Link"