config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'deliver_addresses', to: 'users/registrations#new_deliver_address'
    post 'deliver_addresses', to: 'users/registrations#create_deliver_address'
  end
  root 'products#index'
  resources :users do
    collection do
      get 'logout'
    end
  end
  resources :credit_cards
  resources :brands, only: [:create]
  resources :products do 
    member do
      get 'pay'
      get 'purchase'
    end
    collection do
      get 'paid'
      get 'search_category_children'
      get 'search_category_grandchildren'
      get 'search'
    end
    resources :comments
  end
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates_associated :photos
  validates :name, :introduction, :size_id, :condition_id,
            :postage_payer_id, :prefecture_code, :prep_date_id,
            :price, :trading_status, :seller_id,
            :photos, presence: true
  validates :name, length: { maximum: 40}
  validates :introduction, length: { maximum: 1000}
  validates :price, numericality: { only_integer:true, greater_than_or_equal_to:300, less_than_or_equal_to:9999999}
  has_many :photos, dependent: :destroy
  belongs_to :brand, optional: true
  belongs_to :seller, class_name: 'User', optional: true
  belongs_to :buyer, class_name: 'User', optional: true
  belongs_to :category
  belongs_to_active_hash :size
  belongs_to_active_hash :condition
  belongs_to_active_hash :postage_payer
  belongs_to_active_hash :prep_date
  accepts_nested_attributes_for :photos, allow_destroy: true
  accepts_nested_attributes_for :brand
  scope :search, -> (search) { Product.where('name LIKE(?)', "%#{search}%") }
  scope :prev_search, -> (product) { Product.where("id < ?", product.id).last }
  scope :next_search, -> (product) { Product.where("id > ?", product.id).first }
  enum prefecture_code: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  enum trading_status: {
    出品中:1,売却済み:2
  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: :new
  before_action :find_product, only: [:show, :edit, :update, :purchase, :destroy]
  before_action :admin_seller, only: [:edit, :destroy]

  def index
    @products = Product.includes(:photos).order(created_at: :desc).limit(5)
  end

  def show
    @products = Product.all
    if @product == @products.first
      @next_product = Product.next_search(@product)
    elsif @product == @products.last
      @prev_product = Product.prev_search(@product)
    else
      @prev_product = Product.prev_search(@product)
      @next_product = Product.next_search(@product)
    end
    @grandchild = Category.find(@product.category_id)
    @child = @grandchild.parent
    @parent = @child.parent
    @parent_category_products = @products.select { |product| product.category.root.name == @parent.name }
    @user = current_user
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    @card = CreditCard.find_by(user_id: current_user)
  end

  def new
    @product = Product.new
    @parents = Category.set_parents
    @photos =  @product.photos.build
    @brand = @product.build_brand
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def create
    @product = Product.new(product_params)
    @product.brand.destroy if product_params[:brand_attributes][:name].blank?
    @product.category_id = nil if @product.category && @product.category.children?
    unless @product.valid?
      flash.now[:alert] = @product.errors.full_messages
      @parents = Category.set_parents
      @photos =  @product.photos.build
      @brand = @product.build_brand
      render :new and return
    end
    @product.save
    redirect_to user_path(current_user)
  end

  def update
    @grandchild = Category.find(@product.category_id)
    category =  Category.find_by(id: product_params[:category_id])
    if category && category.children?
      product_params[:category_id] = nil
    end
    brand_name = params[:product][:brand_attributes][:name]
    unless brand_name.empty?
      if @product.update(product_params)
        if params[:destroy_photo_id].present?
          params[:destroy_photo_id].each do |i|
            photo = Photo.find(i)
            if photo.product_id == @product.id
              photo.destroy
            end
          end
        end
        redirect_to user_path(current_user)
      else
        flash.now[:alert] = @product.errors.full_messages
        @parents = Category.set_parents
        @child = @grandchild.parent
        @parent = @child.parent
        @grandchildren = @child.children
        @children = @parent.children
        @prev_images = @product.photos.order(created_at: "ASC")
        @photos =  @product.photos.build
        unless @product.brand.nil?
          brand_name = @product.brand.name
        end
        @brand = @product.build_brand
        render :edit and return
      end
    else
      params[:product].delete(:brand_attributes)
      if @product.update(product_params)
        if params[:destroy_photo_id].present?
          params[:destroy_photo_id].each do |i|
            photo = Photo.find(i)
            if photo.product_id == @product.id
              photo.destroy
            end
          end
        end
        unless @product.brand.nil?
          @product.brand.destroy
          @product.update_attribute(:brand_id, nil)
        end
        redirect_to user_path(current_user)
      else
        flash.now[:alert] = @product.errors.full_messages
        @parents = Category.set_parents
        @child = @grandchild.parent
        @parent = @child.parent
        @grandchildren = @child.children
        @children = @parent.children
        @prev_images = @product.photos.order(created_at: "ASC")
        @photos =  @product.photos.build
        unless @product.brand.nil?
          @brand_name = @product.brand.name
        end
        @brand = @product.build_brand
        render :edit and return
      end
    end
  end

  def edit
    @parents = Category.set_parents
    @grandchild = Category.find(@product.category_id)
    @child = @grandchild.parent
    @parent = @child.parent
    @grandchildren = @child.children
    @children = @parent.children
    @prev_images = @product.photos.order(created_at: "ASC")
    @photos =  @product.photos.build
    unless @product.brand.nil?
      @brand_name = @product.brand.name
    end
    @brand = @product.build_brand
  end

  def search_category_children
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
      end
    end
  end

  def search_category_grandchildren
    respond_to do |format|
      format.html
      format.json do
        @grandchildren = Category.find(params[:child_id]).children
      end
    end
  end

  def purchase
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    @card = CreditCard.find_by(user_id: current_user)
    if @card.blank?
      redirect_to new_credit_card_path
    else
      @customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = @customer.cards.retrieve(@card.card_id)
      @deliver_address = current_user.deliver_address
    end
  end

  def pay
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to new_credit_card_path
    else
      @product = Product.find(params[:id])
      unless @product.buyer_id.nil?
        redirect_to purchase_product_path(@product) and return
      end
      @product.update(buyer_id: current_user.id)
      Payjp::Charge.create(
        :amount => @product.price, 
        :customer => @card.customer_id,
        :currency => 'jpy',
      )
      redirect_to paid_products_path
    end
  end

  def search
    @products = Product.search(params[:keyword]).page(params[:page])
    @parents = Category.set_parents
  end

  private
    def product_params
      params.require(:product).permit(:name, :introduction, :size_id,
                                      :condition_id, :postage_payer_id, :prefecture_code,
                                      :prep_date_id, :price, :trading_status,
                                      :closed_deal_date, :category_id,
                                      photos_attributes:[:image, :product_id],
                                      brand_attributes:[:name]
                                     ).merge(seller_id: current_user.id)
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def admin_seller
      unless current_user.id == @product.seller_id
        redirect_to product_path
      end
    end
end

app/views/products/edit.html.haml
.ProductsNew
  %header.ProductsNew__header
    = link_to image_tag('logo.png'), products_path
  .breadCrumb-nav
    - breadcrumb :products_edit
    = breadcrumbs separator: " &rsaquo; ", class: "breadCrumb-nav__list"
  .ProductsNew__main
    = form_with model: @product, url: product_path(@product), class: "ProductsNew__main__form", local: true do |product|
      = render 'devise/shared/error_messages', resource: @product
      .ProductsNew__main__form__group
        = product.fields_for :photos, @photos do |photo|
          .ProductsNew__main__form__group__field
            %label.field-label 出品画像
            %span 必須
            %h3 最大10枚までアップロードできます
            .ProductsNew__main__form__group__field__file-input
              #files
                = photo.file_field :image, name: "product[photos_attributes][#{@prev_images.count}][image]", id: "filearea#{@prev_images.count}", class: "fileinput fileinput#{@prev_images.count}"
                %label{class: "file-label", for: "filearea#{@prev_images.count}"}
                  = icon('fa', 'camera')
                  %p クリックしてファイルをアップロード
                .ProductsNew__main__form__group__field__file-input__prevbox.prev_box
                  - @prev_images.each do |prev_image|
                    .ProductsNew__main__form__group__field__file-input__prevbox__image.prev_count
                      = image_tag prev_image.image.url
                      %p.deleteprev 削除
                    = check_box_tag :"destroy_photo_id[]", prev_image.id

      .ProductsNew__main__form__group
        .ProductsNew__main__form__group__field
          = product.label '商品名', class: "field-label"
          %span 必須
          .ProductsNew__main__form__group__field__input
            = product.text_field :name, placeholder: '40文字まで'
        .ProductsNew__main__form__group__field
          = product.label '商品の説明', class: "field-label"
          %span 必須
          .ProductsNew__main__form__group__field__input
            = product.text_area :introduction, maxlength: "1000", placeholder: "商品の説明(必須1,000文字以内)(色、素材、重さ、定価、注意点など)例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

      .ProductsNew__main__form__group
        .ProductsNew__main__form__group__field
          %p 商品の詳細
          = product.label 'カテゴリー', class: "field-label"
          %span 必須
          .ProductsNew__main__form__group__field__category-input
            = product.collection_select :category_id, @parents, :id, :name, { selected: @parent.id, prompt: '---' }, { id: 'category_parent' }
            = product.collection_select :category_id, @children, :id, :name, { selected: @child.id, prompt: '---' }, { id: 'category_child' }
            = product.collection_select :category_id, @grandchildren, :id, :name, { selected: @grandchild.id, prompt: '---' }, { id: 'category_grandchild' }
        .ProductsNew__main__form__group__field#size-field-edit
          = product.label 'サイズ', class: "field-label"
          %span 必須
          .ProductsNew__main__form__group__field__input
            = product.collection_select :size_id, Size.all, :id, :name, prompt: '---'
        .ProductsNew__main__form__group__field   
          = product.fields_for :brand, @brand do |brand|
            = brand.label "ブランド", class: "field-label"
            %span.optional 任意
            .ProductsNew__main__form__group__field__input
              - if @brand_name
                = brand.text_field :name, value: @brand_name, placeholder: '例) シャネル'
              - else
                = brand.text_field :name, placeholder: '例) シャネル'
        .ProductsNew__main__form__group__field
          = product.label '商品の状態', class: "field-label"
          %span 必須
          .ProductsNew__main__form__group__field__input
            = product.collection_select :condition_id, Condition.all, :id, :name, prompt: '---'
          
        .ProductsNew__main__form__group
          .ProductsNew__main__form__group__field
            %p
              配送について
              = link_to '？', '#', class: "help"
            = product.label '配送料の負担', class: "field-label"
            %span 必須
            .ProductsNew__main__form__group__field__input
              = product.collection_select :postage_payer_id, PostagePayer.all, :id, :name, prompt: '---'
          .ProductsNew__main__form__group__field
            = product.label '発送元の地域', class: "field-label"
            %span 必須
            .ProductsNew__main__form__group__field__input
              = product.select :prefecture_code, Product.prefecture_codes.keys.to_a, prompt: '---'
          .ProductsNew__main__form__group__field
            = product.label '発送までの日数', class: "field-label"
            %span 必須
            .ProductsNew__main__form__group__field__input
              = product.collection_select :prep_date_id, PrepDate.all, :id, :name, prompt: '---'

        .ProductsNew__main__form__group
          .ProductsNew__main__form__group__field
            %p
              価格(￥300〜9,999,999)
              = link_to '？', '#', class: "help"
            .ProductsNew__main__form__group__field__price-input
              .ProductsNew__main__form__group__field__price-input__label
                = product.label '販売価格', class: "field-label"
                %span 必須
              .ProductsNew__main__form__group__field__price-input__value
                %span.price ￥
                = product.number_field :price, placeholder: "0"
          .ProductsNew__main__form__group__field
            .ProductsNew__main__form__group__field__button
              = product.submit '更新する'
          .ProductsNew__main__form__group__field__link
            = link_to 'もどる', '#'
  %footer.ProductsNew__footer
    .ProductsNew__footer__links
      %ul
        %li
          = link_to 'プライバシーポリシー', '#'
        %li
          = link_to 'furima利用規約', '#'
        %li
          = link_to '特定商取引に関する表記', '#'
    .ProductsNew__footer__logo
      = link_to image_tag('logo-white.png'), products_path
    .ProductsNew__footer__caption
      %p © Furima, Inc.

app/views/products/index.html.haml
%header.header-index
  = render 'shared/header'

.main

  %section.mainvisual
    .content
      %h2.content_title
        %br
          人生を変えるフリマアプリ
      %p.content_text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .content_btn
        = link_to '#', class: 'btn_app' do
          = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg'
        = link_to '#', class: 'btn_google' do
          = image_tag 'http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg'


  %section.topIntroduction
    %h2.title
      FURIMAが選ばれる３つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag 'pict-reason-01.jpg', class: 'pic';
        %h3.list__text
          %span.text 3分
          ですぐに出品
        %p.description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          = image_tag 'pict-reason-02.jpg', class: 'pic';
        %h3.list__text
          %span.text シンプル
          で使いやすい
        %p.description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        .list__pict
          %span.number 3
          = image_tag 'pict-reason-03.jpg', class: 'pic';
        %h3.list__text
          手数料
          %span.text 
            業界最安
        %p.description
          最大3%でお得に出品&購入！


  %section.topMiddleDl
    .content
      %h2.title
        会員数日本一位
      %p.text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to '#', class: 'btn_app' do
          = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg'
        = link_to '#', class: 'btn_google' do
          = image_tag 'http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg'


  %section.topKeysfutures
    %h2.head
      FURIMAの特徴
    .items
      %section.item
        %figure.item__img
          = image_tag 'icon-01.png', class: 'item__img__icon'
        %h3.item__title
          簡単に売り買いできる
        %p.tem__content
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__img
          = image_tag 'icon-03.png', class: 'item__img__icon'
        %h3.item__title
          売上金は即日振込みに対応
        %p.item__content
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.item
        %figure.item__img
          = image_tag 'icon-04.png', class: 'item__img__icon'
        %h3.item__title
          様々な支払いに対応
        %p.item__content
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。


  %section.pickupContainer
    .pickupContainer__group
      .pickupContainer__group__title
        %h2 ピックアップカテゴリー
        %p 新規投稿商品
      .pickupContainer__group__field
        - @products.each do |product|
          .pickupContainer__group__field__product
            = link_to '', product_path(product), class: ".pickupContainer__group__field__product__link"
            .pickupContainer__group__field__product__img
              = image_tag product.photos.first.image.url
              -if product.buyer_id.present? 
                .pickupContainer__group__field__product__sold
                  .pickupContainer__group__field__product__sold__inner SOLD
            .pickupContainer__group__field__product__info
              %p
                = product.name
              .pickupContainer__group__field__product__info__price
                %p
                  = "#{product.price}円"
                %p
                  = icon('fa', 'star')
                  1
              %p.tax (税込)

    .pickupContainer__group
      .pickupContainer__group__title
        %h2 ピックアップブランド
        %p アーカイバ
      .pickupContainer__group__field
        - @products.each do |product|
          .pickupContainer__group__field__product
            = link_to '', product_path(product), class: ".pickupContainer__group__field__product__link"
            .pickupContainer__group__field__product__img
              = image_tag product.photos.first.image.url
            .pickupContainer__group__field__product__info
              %p
                = product.name
              .pickupContainer__group__field__product__info__price
                %p
                  = "#{product.price}円"
                %p
                  = icon('fa', 'star')
                  1
              %p.tax (税込)

.appbar
  .content
    %h2.content_title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.content_text
      今すぐ無料ダウンロード！
      .content_btn
        = link_to '#', class: 'btn_app' do
          = image_tag 'http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg'
        = link_to '#', class: 'btn_google' do
          = image_tag 'http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg'


.footer
  %ul.contents
    %li.content
      %h2.content_header FURIMAについて
      %ul
        %li 
          = link_to "会社概要（運営会社）" , "#"  
        %li
          = link_to "プライバシーポリシー" , "#" 
        %li
          = link_to " FURIMA利用規約" , "#"
        %li
          = link_to "ポイントに関する特約" , "#" 
    %li.content
      %h2.content_header FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧" , "#" 
        %li
          = link_to "ブランド一覧" , "#" 
    %li.content
      %h2.content_header ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド" , "#" 
        %li
          = link_to "FURIMAロゴ利用ガイドライン" , "#" 
        %li
          = link_to "お知らせ" , "#" 
  .footer-logo
    = link_to '#', class: 'logo' do
      = image_tag "logo-white.png"
  %p ©  FURIMA


  .exhibition
    = link_to new_product_path, class:'exhibition__link' do
      .exhibition_btn
        %span.text
          出品する
        = image_tag 'icon_camera.png', class: 'camera'

app/views/products/paid.html.haml
%header.header-index
  = render 'shared/header'

.paid_main 
  .paid_main__message
    購入が完了しました
    %br
    = link_to 'トップページに戻る', root_path, class: "link"

app/views/products/purchase.html.haml
.ProductsPurchase
  %header.ProductsNew__header
    = link_to image_tag('logo.png'), products_path
    
  .breadCrumb-nav
    - breadcrumb :products_purchase
    = breadcrumbs separator: " &rsaquo; ", class: "breadCrumb-nav__list"

  .ProductsPurchase__main

    .ProductsPurchase__main__group
      %h2 購入内容の確認

    .ProductsPurchase__main__group
      .ProductsPurchase__main__group__product-field
        = image_tag @product.photos.first.image.url
        .ProductsPurchase__main__group__product-field__info
          %p
            = @product.name
          .ProductsPurchase__main__group__product-field__info__price
            - if @product.postage_payer_id == 1
              %p
              送料込み(税込)
              %span.yen
                = "￥#{@product.price}"
            - else
              %p
              着払い(税込)
              %span.yen
                = "￥#{@product.price}"

    .ProductsPurchase__main__group
      .ProductsPurchase__main__group__price-field
        %ul
          %li 支払い金額
          %li
            = "￥#{@product.price}"
      .ProductsPurchase__main__group__point-field
        .ProductsPurchase__main__group__point-field__icon
          %span.square
          = icon('fa','dice-d6')
          %p ポイントの使用
        .ProductsPurchase__main__group__point-field__value
          %p 所持ポイント：P0

    .ProductsPurchase__main__group
      .ProductsPurchase__main__group__card-field
        .ProductsPurchase__main__group__card-field__payment
          %p 支払い方法
          = link_to '#' do
            変更する
            %span >
        .ProductsPurchase__main__group__card-field__info
          - if @card.present?
            %p <カード情報> 
            カード番号：
            = "**** **** **** #{@card_information.last4}"
            %br
            有効期限：
            = "#{@card_information.exp_month.to_s} / #{@card_information.exp_year.to_s.slice(2,3)}"
            %br
          - else
            = link_to new_credit_card_path do
              = icon('fa', 'plus-circle')
              ここから登録してください

    .ProductsPurchase__main__group
      .ProductsPurchase__main__group__deliver-field
        .ProductsPurchase__main__group__deliver-field__link
          %p 配送先
          = link_to '#' do
            変更する
            %span >
        .ProductsPurchase__main__group__deliver-field__address
          %p
            = "〒 #{@deliver_address.post_code}"
          - if @deliver_address.building_name.nil?
            %p
              = "#{@deliver_address[:prefecture_code]} #{@deliver_address.city} #{@deliver_address.house_number}"
          - else
            %p
              = "#{@deliver_address[:prefecture_code]} #{@deliver_address.city} #{@deliver_address.house_number} #{@deliver_address.building_name}"
          %p
            = "#{@deliver_address.destination_family_name} #{@deliver_address.destination_first_name}"
    .ProductsPurchase__main__button-group
      - if @card.blank?
        %p 支払い方法の入力を完了してください。
      .ProductsPurchase__main__button-group__field
        - if @product.buyer_id.present?
          = link_to '売り切れました', pay_product_path, class: "disabled-button"
        - else 
          = link_to '購入する', pay_product_path, class: "button"
  %footer.ProductsNew__footer
    .ProductsNew__footer__links
      %ul
        %li
          = link_to 'プライバシーポリシー', '#'
        %li
          = link_to 'furima利用規約', '#'
        %li
          = link_to '特定商取引に関する表記', '#'
    .ProductsNew__footer__logo
      = link_to image_tag('logo-white.png'), products_path
    .ProductsNew__footer__caption
      %p © Furima, Inc.

app/views/products/search.html.haml
%header.header-index
  = render 'shared/header'
.products-search__wrapper
  .products-search__wrapper__sidebar
    .products-search__wrapper__sidebar__sort-box
    .products-search__wrapper__sidebar__search-group
      .products-search__wrapper__sidebar__search-group__field
  .products-search__wrapper__main
    .products-search__wrapper__main__heading
      %h2
        - if params[:keyword].present?
          %span.search_keyword
            = params[:keyword]
          の検索結果
        - else
          %span.search_keyword
          検索結果
    .products-search__wrapper__main__contents
      - @products.each do |product|
        .products-search__wrapper__main__contents__product-prev
          .products-search__wrapper__main__contents__product-prev__img
            = image_tag product.photos.first.image.url
            %span
              = "¥#{product.price}"
          .products-search__wrapper__main__contents__product-prev__name
            %p
              = product.name
            .products-search__wrapper__main__contents__product-prev__name__favorite
              %span
                = icon('fa', 'heart')
                1
    .products-search__wrapper__main__pagination
      = paginate @products